# Generated by Django 4.2.5 on 2024-03-05 06:08

from django.db import migrations, models
import hls_service.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('video_file', models.FileField(upload_to=hls_service.models.video_file_upload_path)),
                ('hls_file', models.TextField(null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('size', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
